### ISSUE TITLE
Parse tip dates

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/BelleJS#1]
In BEAUTi, clicking on the "Use tip dates" checkbox activates the other inputs, such as the "Parse Dates" button.
Clicking on "Parse dates" creates a modal window where the user specifies how the app should extract date information from the sequence headers, *e.g.*, delimiter character, position of date in tokens.

**Comment by ewong347** [comment]
Here's what the pop-up dialog + updated table with tip Height looks like:

Formula for tip height = (Days between Most recent tip - current tip /365)

![Screen Shot 2021-03-25 at 11 18 25 AM](https://user-images.githubusercontent.com/44472547/112497344-e5b02a00-8d5b-11eb-9454-8118bcf30525.png)
![Screen Shot 2021-03-25 at 11 18 32 AM](https://user-images.githubusercontent.com/44472547/112497345-e648c080-8d5b-11eb-9ce4-57065268ef1d.png)

**Comment by ArtPoon** [comment]
Cool!  Is this in a different branch?  I'm not seeing this change

**Comment by ewong347** [comment]
Uh I think it should be in 2c1ad81 @ArtPoon ?

I think the first radio button could be removed for simplicity for the lab, but re-added when we wanted to add the other options in BEAUTi. 
Also as an aside should we add the option to define a different format for the date( i.e. mm/yyyy/dd)?

**Comment by ArtPoon** [comment]
Yeah I'm at that commit.  Checkbox is not activating buttons on Tips page for me.

**Comment by ewong347** [comment]
My use case is:

Upload fasta -> switch to tip page ~~(Use tip dates checkbox isn't hooked up to anything right now)~~ -> click parse dates -> select  Defined just by its prefix and its order -> select "last" for order -> type "_" for delimeter -> ok

For fasta files that look like:
```fasta
> CY068313_A_California_VRDL253_2009_2009/04/30
AATG... 
```

**Comment by ewong347** [comment]
Quick update:
9798373 gives tip dates checkbox the ability to disable/enable the button options underneath including parse dates

**Comment by ArtPoon** [comment]
Looks great!  I had a couple of 404 errors in my console:
```
Failed to load resource: the server responded with a status of 404 (File not found)
ui-icons_777777_256x240.png:1
Failed to load resource: the server responded with a status of 404 (File not found) 
ui-icons_444444_256x240.png:1 
```

**Comment by ewong347** [comment]
Those look like jquery-ui resources? Might be a local issue, I'm not seeing those on my end.

What other functionality would we want from this table?
For the (#3), this tip data (including Height & parsed date) are found in the object ```new_data``` currently.

**Comment by ArtPoon** [comment]
Whatever needs to be embedded in the XML.  I got XML to read in from a file, which will help keep it similar to what BEAST expects.
