### ISSUE TITLE
Running BEAST v1.10.4 on the generated XML file

### ISSUE THREAD

**Issue by GopiGugan** [ArtPoon/BelleJS#11]
Getting the following error when running BEAST on the generated `YFV.xml` file:
```
SEVERE: Parsing error - poorly formed BEAST file, YFV.xml:
Object with Id=2009_TVP11767_Trinidad already exists

Error thrown at: dr.xml.XMLParser.convert(Unknown Source)
```

**Comment by ArtPoon** [comment]
Hm, I am able to run `YFV.xml` generated by Belle on the server - can you send me your copy so I can compare?

**Comment by GopiGugan** [comment]
Thanks @ArtPoon. Works now after doing a hard reset.
