### ISSUE TITLE
Need to bind contents of Priors tab to other tabs

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/BelleJS#2]
@ewong347 suggested creating persistent Prior objects for every possible model combination, which is a good idea (we can also have a many-to-one mapping when models share the same prior).

**Comment by ewong347** [comment]
Starting with the strict clock and uncorrelated lognormal clock models

**Comment by ewong347** [comment]
Unassigning for now until I can take another whack at it

**Comment by ArtPoon** [comment]
@GopiGugan I am disabling all clock models other than strict and uncorrelated lognormal
For Trees, I am disabling all models except for `Coalescent: Constant Size` and `Coalescent: Bayesian Skyline`
