### ISSUE TITLE
Starting Tree tab?

### ISSUE THREAD

**Issue by ewong347** [ArtPoon/BelleJS#4]
Should we include this tab?

To change tree type to cluster Tree, and cluster tree type to neighbourjoining. (working off my previous year's BEAST lab)

**Comment by ArtPoon** [comment]
No, we're just trying to get basic functionality first. Thanks!

**Comment by ArtPoon** [comment]
Also the interface is being modeled on BEAUTI version 1.10.4

**Comment by ArtPoon** [comment]
Right now I have only Random tree and UPGMA (hierarchical clustering) options available for setting the initial tree.
